version: '3.8'
services:
  ubntmvn:
    build: ubntmvn-custom
    volumes:
      - ./tget:/root/webapps/


  tomcat:
    image: amd64/tomcat:9.0
    volumes:
      - ./tget:/usr/local/tomcat/webapps/
    links:
      - ubntmvn
    ports:
      - "80:8080"
