version: '3.8'
services:
  ubntmvn:
    build: ubntmvn-custom
    volumes:
      - ./target:/root/boxfuse-sample-java-war-hello/target/

  tomcat:
    image: amd64/tomcat:9.0
    volumes:
      - ./target:/usr/local/tomcat/webapps/
    links:
      - ubntmvn
    ports:
      - "80:8080"
