version: '3.8'
services:
  ubntmvn:
    build: ubntmvn-custom
    volumes:
      - type: volume
        source: tget
        target: /home

  tomcat:
    image: amd64/tomcat:9.0
    volumes:
      - ./target:/usr/local/tomcat/webapps/
    links:
      - ubntmvn
    ports:
      - "80:8080"

volumes:
  tget: