version: '3.8'
services:
  ubntmvn:
    build: ubntmvn-custom
    volumes:
      - type: volume
        source: vol1
        target: /root/webapps


  tomcat:
    image: amd64/tomcat:9.0
    volumes:
      - type: volume
        source: vol1
        target: /usr/local/tomcat/webapps
    links:
      - ubntmvn
    ports:
      - "80:8080"

volumes:
  vol1: